"""add missing columns

Revision ID: 656f06f81c5e
Revises: d6da2ad9acaa
Create Date: 2026-03-19 12:30:35.510312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656f06f81c5e'
down_revision: Union[str, Sequence[str], None] = 'd6da2ad9acaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'offer_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('applications', 'applicant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('applications', 'career',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('applications', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('applications', 'gpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('applications', 'availability',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'flexible'::character varying"))
    op.alter_column('applications', 'motivation_letter',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('offers', 'requirements',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('offers', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('offers', 'requirements',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('applications', 'motivation_letter',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('applications', 'availability',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'flexible'::character varying"))
    op.alter_column('applications', 'gpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('applications', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('applications', 'career',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('applications', 'applicant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('applications', 'offer_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
