"""add missing columns

Revision ID: d6da2ad9acaa
Revises: b2c3d4e5f6a7
Create Date: 2026-03-19 12:27:25.819963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6da2ad9acaa'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns as nullable to avoid NOT NULL violation on existing rows
    op.add_column('applications', sa.Column('offer_title', sa.String(length=200), nullable=True, server_default=''))
    op.add_column('applications', sa.Column('applicant_name', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('applications', sa.Column('career', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('applications', sa.Column('semester', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('applications', sa.Column('gpa', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('applications', sa.Column('availability', sa.String(length=20), nullable=True, server_default='flexible'))
    op.add_column('applications', sa.Column('motivation_letter', sa.Text(), nullable=True, server_default=''))
    op.alter_column('applications', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'student_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.add_column('offers', sa.Column('requirements', sa.Text(), nullable=True, server_default=''))
    op.add_column('offers', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('location', sa.String(length=200), nullable=True, server_default=''))
    op.alter_column('offers', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('offers', 'staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('offers', 'location')
    op.drop_column('offers', 'deadline')
    op.drop_column('offers', 'requirements')
    op.alter_column('applications', 'student_email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('applications', 'student_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('applications', 'motivation_letter')
    op.drop_column('applications', 'availability')
    op.drop_column('applications', 'gpa')
    op.drop_column('applications', 'semester')
    op.drop_column('applications', 'career')
    op.drop_column('applications', 'applicant_name')
    op.drop_column('applications', 'offer_title')
    # ### end Alembic commands ###
